sed -i 's/\([^_]\)MAXCPU/\1MAX_NUM_CPUS/g' $*
sed -i 's/curcpu/hw_core_id()/g' $*
sed -i 's/MSR_PAT/MSR_IA32_CR_PAT/g' $*
sed -i 's/CR4_XSAVE/X86_CR4_OSXSAVE/g' $*
sed -i 's/boolean_t/bool/g' $*
sed -i 's/MSR_VMX_BASIC/MSR_IA32_VMX_BASIC/g' $*
sed -i 's/MSR_VMX_PROCBASED_CTLS/MSR_IA32_VMX_PROCBASED_CTLS/g' $*
sed -i 's/MSR_VMX_TRUE_PROCBASED_CTLS/MSR_IA32_VMX_TRUE_PROCBASED_CTLS/g' $*
sed -i 's/MSR_VMX_PROCBASED_CTLS2/MSR_IA32_VMX_PROCBASED_CTLS2/g' $*
sed -i 's/MSR_VMX_PINBASED_CTLS/MSR_IA32_VMX_PINBASED_CTLS/g' $*
sed -i 's/MSR_VMX_TRUE_PINBASED_CTLS/MSR_IA32_VMX_TRUE_PINBASED_CTLS/g' $*
sed -i 's/MSR_VMX_EXIT_CTLS/MSR_IA32_VMX_EXIT_CTLS/g' $*
sed -i 's/MSR_VMX_TRUE_EXIT_CTLS/MSR_IA32_VMX_TRUE_EXIT_CTLS/g' $*
sed -i 's/MSR_VMX_ENTRY_CTLS/MSR_IA32_VMX_ENTRY_CTLS/g' $*
sed -i 's/MSR_VMX_TRUE_ENTRY_CTLS/MSR_IA32_VMX_TRUE_ENTRY_CTLS/g' $*
sed -i 's/MSR_VMX_CR0_FIXED0/MSR_IA32_VMX_CR0_FIXED0/g' $*
sed -i 's/MSR_VMX_CR0_FIXED1/MSR_IA32_VMX_CR0_FIXED1/g' $*
sed -i 's/MSR_VMX_CR4_FIXED0/MSR_IA32_VMX_CR4_FIXED0/g' $*
sed -i 's/MSR_VMX_CR4_FIXED1/MSR_IA32_VMX_CR4_FIXED1/g' $*
sed -i 's/IA32_FEATURE_CONTROL_LOCK/FEATURE_CONTROL_LOCKED/g' $*
sed -i 's/IA32_FEATURE_CONTROL_VMX_EN/FEATURE_CONTROL_VMXON_ENABLED_OUTSIDE_SMX/g' $*
sed -i 's/IDT_BP/T_BRKPT/g' $*
sed -i 's/IDT_OF/T_OFLOW/g' $*
sed -i 's/IDT_BR/T_BOUND/g' $*


sed -i 's/MSR_GSBASE/MSR_GS_BASE/g' $*
sed -i 's/MSR_FSBASE/MSR_FS_BASE/g' $*
